# Generated by Django 4.2.23 on 2025-08-09 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the movie was added to favorites')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes about this movie", max_length=500)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text="User's personal rating (1-5 stars)", null=True)),
                ('movie', models.ForeignKey(help_text='Movie that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
                ('user', models.ForeignKey(help_text='User who favorited the movie', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='favorites_u_user_id_6b17cc_idx'), models.Index(fields=['movie', 'created_at'], name='favorites_u_movie_i_a82ca2_idx'), models.Index(fields=['user', 'rating'], name='favorites_u_user_id_de2a6d_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the favorite list', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this favorite list', max_length=500)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this list is visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this list was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this list was last updated')),
                ('movies', models.ManyToManyField(blank=True, help_text='Movies in this favorite list', related_name='in_favorite_lists', to='movies.movie')),
                ('user', models.ForeignKey(help_text='User who owns this list', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite List',
                'verbose_name_plural': 'Favorite Lists',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='favorites_f_user_id_2380e3_idx'), models.Index(fields=['is_public', 'updated_at'], name='favorites_f_is_publ_903d85_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
