name: Dependency Update

on:
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update requirements
        run: |
          if [ -f requirements/base.in ]; then
            pip-compile --upgrade requirements/base.in
          fi
          if [ -f requirements/development.in ]; then
            pip-compile --upgrade requirements/development.in
          fi
          if [ -f requirements/production.in ]; then
            pip-compile --upgrade requirements/production.in
          fi

      - name: Run security check
        run: |
          pip install safety
          if ! safety check --json --output safety-report.json; then
            echo "Security vulnerabilities found - check safety-report.json"
            # Continue with PR creation to notify about vulnerabilities
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: weekly dependency update"
          body: |
            ## Automated Dependency Update

            This PR contains automated updates to project dependencies.

            ### Changes
            - Updated Python package dependencies
            - Ran security check with Safety

            ### Review Notes
            - Please review the updated dependencies for compatibility
            - Check for any breaking changes in the changelog
            - Ensure all tests pass before merging

            Auto-generated by GitHub Actions 🤖
          branch: chore/update-dependencies
          delete-branch: true
